# Use a python base image
FROM

# set a directory for the app
WORKDIR /usr/src/app

# copy all the files to the container
COPY

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# tell the port number the container should expose
EXPOSE

# run the command
CMD ["python", "./application.py"]
